### PR TITLE
*: convert %f from nanoseconds to microseconds

### PR DESCRIPTION
**Pull request by otan**
Refs: https://github.com/cockroachdb/cockroach/issues/45881

This is not part of the POSIX standard, so we can dictate what to do
here. If we want to match python's example, we should make this 10^6
instead.

### CODE REVIEW

**Comment by otan** [comment]
can't seem to add reviewers, cc @knz for review!

**Comment by knz** [comment]
Maybe ok to print more digits, but what's the problem with allowing more digits on input? The number of digits present dictate the precision?

**Comment by otan** [comment]
Well for one cockroach only supports six digits of precision anyway. It
just matches behaviour of other things out of spec, ie python.

Oliver

**Comment by otan** [comment]
cc @knz mind taking another look?

**Pull request merged**
